apiVersion: jenkins.io/v1
kind: SourceRepositoryGroup
metadata:
  name: comments-service-group
spec:
  scheduler:
    apiVersion: jenkins.io/v1
    kind: Scheduler
    name: default-scheduler
  repositories:
  - apiVersion: jenkins.io/v1
    kind: SourceRepository
    name: cloudsmartio/comments-service
