apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: monstertrux
    provider: github
    repository: cron-service
  name: monstertrux-cron-service
spec:
  description: Imported application for monstertrux/cron-service
  httpCloneURL: https://github.com/monstertrux/cron-service.git
  org: monstertrux
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: cron-service
  scheduler:
    kind: ""
    name: ""
  url: git@github.com:monstertrux/cron-service.git
