adminUser:
  password: vault:cloudsmart-cluster1/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: github@cloudsmart.io
  token: vault:cloudsmart-cluster1/pipelineUser:token
  username: monstertrux
prow:
  hmacToken: vault:cloudsmart-cluster1/prow:hmacToken
